// Code generated by MockGen. DO NOT EDIT.
// Source: ../pool/manager.go
//
// Generated by this command:
//
//	mockgen -source=../pool/manager.go -destination=./pool.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	pool "github.com/kipsilabs/postie/internal/pool"
	gomock "go.uber.org/mock/gomock"
)

// MockPoolManager is a mock of PoolManager interface.
type MockPoolManager struct {
	ctrl     *gomock.Controller
	recorder *MockPoolManagerMockRecorder
	isgomock struct{}
}

// MockPoolManagerMockRecorder is the mock recorder for MockPoolManager.
type MockPoolManagerMockRecorder struct {
	mock *MockPoolManager
}

// NewMockPoolManager creates a new mock instance.
func NewMockPoolManager(ctrl *gomock.Controller) *MockPoolManager {
	mock := &MockPoolManager{ctrl: ctrl}
	mock.recorder = &MockPoolManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolManager) EXPECT() *MockPoolManagerMockRecorder {
	return m.recorder
}

// GetCheckPool mocks base method.
func (m *MockPoolManager) GetCheckPool() pool.NNTPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckPool")
	ret0, _ := ret[0].(pool.NNTPClient)
	return ret0
}

// GetCheckPool indicates an expected call of GetCheckPool.
func (mr *MockPoolManagerMockRecorder) GetCheckPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckPool", reflect.TypeOf((*MockPoolManager)(nil).GetCheckPool))
}

// GetPool mocks base method.
func (m *MockPoolManager) GetPool() pool.NNTPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool")
	ret0, _ := ret[0].(pool.NNTPClient)
	return ret0
}

// GetPool indicates an expected call of GetPool.
func (mr *MockPoolManagerMockRecorder) GetPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockPoolManager)(nil).GetPool))
}

// GetUploadPool mocks base method.
func (m *MockPoolManager) GetUploadPool() pool.NNTPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUploadPool")
	ret0, _ := ret[0].(pool.NNTPClient)
	return ret0
}

// GetUploadPool indicates an expected call of GetUploadPool.
func (mr *MockPoolManagerMockRecorder) GetUploadPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUploadPool", reflect.TypeOf((*MockPoolManager)(nil).GetUploadPool))
}

// GetVerifyPool mocks base method.
func (m *MockPoolManager) GetVerifyPool() pool.NNTPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerifyPool")
	ret0, _ := ret[0].(pool.NNTPClient)
	return ret0
}

// GetVerifyPool indicates an expected call of GetVerifyPool.
func (mr *MockPoolManagerMockRecorder) GetVerifyPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerifyPool", reflect.TypeOf((*MockPoolManager)(nil).GetVerifyPool))
}
